#!/usr/bin/env ansible-playbook

# SPDX-FileCopyrightText: 2022 Maxwell G (@gotmax23)
# SPDX-License-Identifier: MIT
---
- name: Generate files
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    generator_molecule_wflow_test:
      skip_test_step: true
      steps:
        - name: "Molecule test: vscodium_state=present"
          env:
            vscodium_state: present
          run: molecule test -s single --destroy never
        - name: "Molecule test: vscodium_state=absent"
          env:
            vscodium_state: absent
          run: molecule test -s single --destroy never
        - name: Molecule destroy
          if: always()
          run: molecule destroy -s single

  roles:
    - gotmax23.generator

# vim: set filetype=yaml.ansible:
